// Copyright 2026 CyNickal Software LLC
// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0

#include "backtest/backtest_job_tests.h"
#include "backtest/engine_tests.h"
#include "backtest/strategy_tests.h"
#include "catch_amalgamated.hpp"
#include "chart/chart_axis_tests.h"
#include "chart/chart_command_tests.h"
#include "chart/chart_load_tests.h"
#include "chart/chart_study_tests.h"
#include "chart/moving_average_tests.h"
#include "chart/bollinger_tests.h"
#include "chart/n_bar_percent_change_tests.h"
#include "chart/chart_trades_tests.h"
#include "chart/chart_transform_tests.h"
#include "chart/chart_view_tests.h"
#include "data/statement_sheet_tests.h"
#include "data/ledger_analysis_tests.h"
#include "data/ledger_marks_tests.h"
#include "data/portfolio_fetch_tests.h"
#include "risk/historical_risk_tests.h"
#include "trading/equity_curve_tests.h"
#include "trading/ledger_tests.h"
#include "trading/trade_stats_tests.h"
#include "options/option_payoff_tests.h"
#include "options/option_strategy_tests.h"
#include "ui/frame_chrome_tests.h"
#include "ui/received_stamp_tests.h"
#include "ui/trading_format_tests.h"
#include "ui/appearance_settings_tests.h"
#include "ui/command_match_tests.h"
#include "chart/chartbook_file_tests.h"
#include "chart/symbol_link_tests.h"
#include "options/payoff_chartbook_tests.h"
