// Copyright 2026 CyNickal Software LLC
// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0

#include "catch_amalgamated.hpp"
#include "chart/chart_axis_tests.h"
#include "chart/chart_command_tests.h"
#include "chart/chart_load_tests.h"
#include "chart/chart_study_tests.h"
#include "chart/moving_average_tests.h"
#include "chart/bollinger_tests.h"
#include "chart/chart_transform_tests.h"
#include "chart/chart_view_tests.h"
#include "data/statement_sheet_tests.h"
#include "data/portfolio_fetch_tests.h"
#include "options/option_payoff_tests.h"
#include "options/option_strategy_tests.h"
#include "ui/frame_chrome_tests.h"
#include "chart/chartbook_file_tests.h"
#include "chart/symbol_link_tests.h"
#include "options/payoff_chartbook_tests.h"
